name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    permissions:
      contents: read
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install

      - name: Build 🏗️
        run: pnpm run generate

      - name: Deploy 🚀
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy .output/public --project-name=acho-arnold-cm